steps:
    - name: python
      entrypoint: python
      args: ["-m", "pip", "install", "--upgrade", "pip"]
    - name: python
      entrypoint: python
      args: ["-m", "build.py", "--ci"]
options:
  logging: CLOUD_LOGGING_ONLY