name: CI
on:  
  push:
    tags:
      - '*'
jobs:
  build-1:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
    outputs:
      finished: ${{ steps.stage.outputs.finished }}  
  publish-release:
    needs: [build-1]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: chromium
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          fail_on_unmatched_files: true
          files: |
            ungoogled-chromium*
    outputs:
      assets: ${{ steps.publish.outputs.assets }}
  publish-winget:
    needs: publish-release
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/winget
      - name: Run Stage
        id: stage
        uses: ./.github/actions/winget
        with:
          token: ${{ secrets.PAT }}
          version: ${{ github.ref_name }}
          assets: ${{ needs.publish-release.outputs.assets }}
